import { Component } from '@angular/core';
import { environment } from '../../../../../environments/environment';
import { HttpClient } from "@angular/common/http";
import { Router } from '@angular/router';
import { AuthService } from 'app/services/auth.service';
import { TableButtonComponent } from 'app/components/table-button/table-button.component';
import { ExportExcelService } from 'app/services/export-excel.service';

@Component({
  selector: 'ExportReport',
  templateUrl: './export.component.html',
  styleUrls: ['./export.component.css']
})

export class ExportReportComponent {
  data: any[];
  fromPicker: HTMLInputElement;
  toPicker: HTMLInputElement;
  fromDate: string;
  toDate: string;
  excelData: any[] = [];
  total: number;
  gst: number;
  admin: number;
  tds: number;
  gstCheckbox: HTMLInputElement;
  tdsCheckbox: HTMLInputElement;
  adminCheckbox: HTMLInputElement;
  dataFetched: boolean = false;

  settings = {
    mode: 'external',
    selectedRowIndex: -1,
    columns: {
      "Pin": {
        title: 'Pin',
      },
      "Generated By": {
        title: 'Generated For',
        width: '30%'
      },
      "Used By": {
        title: 'Used By',
        width: '30%'
      },
      "Generated On": {
        title: 'Date-Time',
        filter: false,
      },
      // action: {
      //   title: 'Actions',
      //   filter: false,
      //   type: 'custom',
      //   width: '80px',
      //   renderComponent: TableButtonComponent,
      //   onComponentInitFunction: (instance) => {
      //     instance.buttonText = 'Proceed';
      //     instance.rowData = instance.row;
      //     instance.hidable = false;
      //     instance.onClick.subscribe(() => {
      //       this.showDetailedPopup(
      //         instance.rowData["User ID"],
      //         instance.rowData.Name,
      //         instance.rowData["Phone No"],
      //         instance.rowData.Email,
      //         instance.rowData.Sponsor,
      //         instance.rowData.Username,
      //         instance.rowData["Registered On"],
      //         instance.rowData.bank_ac_holder_name,
      //         instance.rowData.ifsc_code,
      //         instance.rowData.bank_name,
      //         instance.rowData.branch,
      //         instance.rowData.ac_no,
      //         instance.rowData.pan_no,
      //         instance.rowData.aadhar_no,
      //       );
      //     })
      //   },
      // }
    },
    pager: {
      perPage: 10,
    },
    actions: {
      add: false,
      edit: false,
      delete: false,
    },
    editable: false,
  };

  constructor(private http: HttpClient, private router: Router, private authService: AuthService, private excelService: ExportExcelService) { }

  ngOnInit() {
    if (!this.authService.isAuthenticated()) {
      this.router.navigate(['/login']);
    } else { 
      this.fromPicker = document.getElementById('fromPicker') as HTMLInputElement;
      this.fromPicker.max = new Date().toLocaleDateString('fr-ca');
      this.toPicker = document.getElementById('toPicker') as HTMLInputElement;
      this.toPicker.max = new Date().toLocaleDateString('fr-ca');
      this.adminCheckbox = document.getElementById('adminCheckbox') as HTMLInputElement;
      this.tdsCheckbox = document.getElementById('tdsCheckbox') as HTMLInputElement;
      this.gstCheckbox = document.getElementById('gstCheckbox') as HTMLInputElement;
    }
  }

  generateReport() {
    if (this.fromPicker.value != '' && this.toPicker.value != '') {
      var param = {
        "param": {
          "from": this.fromPicker.value,
          "to": this.toPicker.value,
        }
      }
      this.http.post<{ data: any, total: number, admin: number, tds: number, gst: number, message: string }>(environment.apiBaseUrl + '/api/GetReportData', param).subscribe(response => {
        this.data = response.data;
        this.total = response.total;
        this.gst = response.gst;
        this.admin = response.admin;
        this.tds = response.tds;
        this.dataFetched = true;
        setTimeout(() => {
          document.getElementById('GSTLabel').textContent = 'Rs. ' + response.gst.toString() + ' (18%)'
          document.getElementById('TDSLabel').textContent = 'Rs. ' + response.tds.toString() + ' (5%)'
          document.getElementById('adminLabel').textContent = 'Rs. ' + response.admin.toString() + ' (10%)'
          document.getElementById('totalamountLabel').textContent = 'Rs. ' + response.total.toString() + ' (100%)'
        }, 100);
        this.fromDate = this.fromPicker.value
        this.toDate = this.toPicker.value
      }, error => {
        console.error(error);
      });
    } else {
      alert('Error : Select Date!')
    }
  }

  exportToExcel() {
    this.data.forEach((row: any) => {
      this.excelData.push(Object.values(row))
      console.log(Object.values(row))
    })
    let reportData = {
      title: this.fromDate + ' - ' + this.toDate + ' Report (Physics Marketing)',
      data: this.excelData,
      headers: Object.keys(this.data[0])
    }
    var gstAmt, tdsAmt, adminAmt;
    if (this.gstCheckbox.checked) gstAmt = this.gst; else gstAmt = null
    if (this.tdsCheckbox.checked) tdsAmt = this.tds; else tdsAmt = null
    if (this.adminCheckbox.checked) adminAmt = this.admin; else adminAmt = null
    this.excelService.export(reportData, this.total, gstAmt, adminAmt, tdsAmt);
  }
}
