# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Client CI

on: 
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./client/

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './client/package-lock.json'
        
    - run: npm install --global @angular/cli --force
      working-directory: client
      
    - run: npm install --force
      working-directory: client
    
    - run: ng build --configuration production
      working-directory: client

    - run: pm2 delete pm-client
    - run: pm2 serve dist 4200 --name pm-client
