name: Production CI

on: 
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
      
    - name: Install client packages
      run: npm install --force
      working-directory: client
    
    - name: Build Client Project
      run: ng build --configuration production --output-path=build
      working-directory: client

    - name: Delete old serving process
      run: pm2 delete pm-client
      working-directory: client

    - name: Serve latest build
      run: pm2 serve build 4200 --name pm-client
      working-directory: client

    - name: Setup API environment
      env:
        MSSQL_USER: ${{ secrets.MSSQL_USER }}
        MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
        MSSQL_SERVER: ${{ secrets.MSSQL_SERVER }}
        EMAIL_ID: ${{ secrets.EMAIL_ID }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: |
        echo "MSSQL_USER=$MSSQL_USER" >> .env
        echo "MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD" >> .env
        echo "MSSQL_SERVER=$MSSQL_SERVER" >> .env
        echo "EMAIL_ID=$EMAIL_ID" >> .env
        echo "EMAIL_PASS=$EMAIL_PASS" >> .env
      working-directory: api

    - name: Install API packages
      run: npm install --force
      working-directory: api

    - name: Delete old api process
      run: pm2 delete pm-api
      working-directory: api
    
    - name: Serve latest API changes
      run: pm2 start server.js --name pm-api
      working-directory: api